In [1]:
import numpy as np

In [2]:
3.7e-16/1.6e-19

2312.5

In [3]:
np.array( [8e-17,-3.2e-16,-4.8e-16] ) / -1.6e-19

array([-500., 2000., 3000.])

In [15]:
np.array( [4.5e-5,-4.5e5,0] ) / 5e-9 * -6e-9

array([-5.4e-05,  5.4e+05, -0.0e+00])

In [51]:
def calc_field_point(rsrc,qsrc,robs):
    k = 9e9
    rsrc = np.array(rsrc)
    robs = np.array(robs)
    r = robs - rsrc
    rmag = np.sqrt( np.dot(r,r) )
    rhat = r / rmag
    print( "rsrc: {}".format(rsrc) )
    print( "robs: {}".format(robs) )
    print( "r = robs-rsrc = {}".format(r) )
    print( "|r|={:.4f}".format(rmag))
    print( "rhat={}".format(rhat))
    Emag = k * qsrc / rmag**2
    print( "E = (9e9)({})/{:.4f} <{}>".format(qsrc,rmag**2,rhat))
    print( "|E|={:.4E}".format(Emag))
    E = Emag * rhat
    print( "E = {}".format(Emag*rhat))
    return E

In [47]:
calc_field_point( [0,0],4e-9,[-.1,-.1] )

rsrc: [0 0]
robs: [-0.1 -0.1]
r = robs-rsrc = [-0.1 -0.1]
|r|=0.1414
rhat=[-0.70710678 -0.70710678]
E = (9e9)(4e-09)/0.0200[-0.70710678 -0.70710678]
|E|=1.8000E+03
E = [-1272.79220614 -1272.79220614]


array([-1272.79220614, -1272.79220614])

In [52]:
calc_field_point( [0.4,0,0],-1e-9,[0.2,0,0])

rsrc: [0.4 0.  0. ]
robs: [0.2 0.  0. ]
r = robs-rsrc = [-0.2  0.   0. ]
|r|=0.2000
rhat=[-1.  0.  0.]
E = (9e9)(-1e-09)/0.0400 <[-1.  0.  0.]>
|E|=-2.2500E+02
E = [225.  -0.  -0.]


array([225.,  -0.,  -0.])

In [53]:
calc_field_point( [0,0,0],-1e-9,[0.12,0,0])

rsrc: [0 0 0]
robs: [0.12 0.   0.  ]
r = robs-rsrc = [0.12 0.   0.  ]
|r|=0.1200
rhat=[1. 0. 0.]
E = (9e9)(-1e-09)/0.0144 <[1. 0. 0.]>
|E|=-6.2500E+02
E = [-625.   -0.   -0.]


array([-625.,   -0.,   -0.])

In [60]:
E2 = calc_field_point( [0,0],8e-6,[0,.04] ) / 1e7

rsrc: [0 0]
robs: [0.   0.04]
r = robs-rsrc = [0.   0.04]
|r|=0.0400
rhat=[0. 1.]
E = (9e9)(8e-06)/0.0016 <[0. 1.]>
|E|=4.5000E+07
E = [       0. 45000000.]


In [64]:
E3 = calc_field_point( [.03,0],-5e-6,[0,0.04] ) / 1e7

rsrc: [0.03 0.  ]
robs: [0.   0.04]
r = robs-rsrc = [-0.03  0.04]
|r|=0.0500
rhat=[-0.6  0.8]
E = (9e9)(-5e-06)/0.0025 <[-0.6  0.8]>
|E|=-1.8000E+07
E = [ 10800000. -14400000.]


In [69]:
E1 = calc_field_point( [0,0.04],3e-6,[0.03,0.04] )

rsrc: [0.   0.04]
robs: [0.03 0.04]
r = robs-rsrc = [0.03 0.  ]
|r|=0.0300
rhat=[1. 0.]
E = (9e9)(3e-06)/0.0009 <[1. 0.]>
|E|=3.0000E+07
E = [30000000.        0.]


In [70]:
E2 = calc_field_point( [0,0],8e-6,[0.03,0.04] )

rsrc: [0 0]
robs: [0.03 0.04]
r = robs-rsrc = [0.03 0.04]
|r|=0.0500
rhat=[0.6 0.8]
E = (9e9)(8e-06)/0.0025 <[0.6 0.8]>
|E|=2.8800E+07
E = [17280000.         23039999.99999999]


In [75]:
E3 = calc_field_point( [0.03,0],-5e-6,[.03,.04] )

rsrc: [0.03 0.  ]
robs: [0.03 0.04]
r = robs-rsrc = [0.   0.04]
|r|=0.0400
rhat=[0. 1.]
E = (9e9)(-5e-06)/0.0016 <[0. 1.]>
|E|=-2.8125E+07
E = [       -0. -28125000.]


In [77]:
sum( [E1,E2,E3] ) / 1e7

array([ 4.728 , -0.5085])

In [80]:
ma = 6.8e-27

In [86]:
-1.63e-12/ma / 1e14

-2.3970588235294117

In [87]:
1.6e-19*6e-10

9.6e-29

In [90]:
2*9e9*9.6e-29/(4e-8)**3 *1.6e-19

4.319999999999999e-15